### ISSUE TITLE
incompatible dimensions when plotting

### ISSUE THREAD

**Issue by stephanlphilips** [QCoDeS/broadbean#46]
Hi,

I had some trouble when running the following code:

bp1.setSR(1e9)
bp1.insertSegment(0, ramp, (0, 1e-3), name='', ts=1, durs=20e-9)
bp1.insertSegment(1, ramp, ( 1e-3,  1e-3), name='', ts=1, durs=30e-9)
bp1.plot()

One gets the error: 
 File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 244, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (50,) and (49,)

**Comment by WilliamHPNielsen** [comment]
HI @stephanlphilips. Hopefully the issue you mention should be fixed by #44. Can you update and check if that's the case?
